
import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Propvator",
  description: "Compare different prop firms and select with confidence Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`overflow-x-hidden`}>
      <head>

        
        <Script
          strategy="lazyOnload"
          src={`https://www.googletagmanager.com/gtag/js?id=G-4NZ0FFNZ1N`}
        />

        <Script id="ga-script" strategy="lazyOnload">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-4NZ0FFNZ1N', {
              page_path: window.location.pathname,
            });
        `}
        </Script>

        {/* LiveChat Script */}
        <Script 
          id="livechat-script" 
          strategy="lazyOnload"
          src="https://accounts.livechat.com/join?access_token=dal:vhkV6BXUUHqh30v2Td0spRZgbo0"
        />

        
      </head>
      <body className={`${inter.className} overflow-x-hidden`}>{children}</body>
    </html>
  );
}
