import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Propvator",
  description: "Compare different prop firms and select with confidence Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`overflow-x-hidden`}>
      <body className={`${inter.className} overflow-x-hidden`}>{children}</body>
    </html>
  );
}
